blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/marreiro23/shp-mgmt-api/security/advisories/new
    about: Use este canal para reportar vulnerabilidades.
